#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 08, 2020 08:54:32 PM +0430  platform: Linux
#    Sep 08, 2020 08:55:33 PM +0430  platform: Linux
#    Sep 08, 2020 08:57:56 PM +0430  platform: Linux
#    Sep 08, 2020 08:58:38 PM +0430  platform: Linux
#    Sep 08, 2020 09:03:02 PM +0430  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global che71
    che71 = tk.IntVar()
    global check_var
    check_var = tk.StringVar()
    global che70
    che70 = tk.IntVar()
    global che65
    che65 = tk.IntVar()
    global selectedButton
    selectedButton = tk.StringVar()
    global tch69
    tch69 = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def chbxpressed():
    print('unknown_support.chbxpressed')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()





